Inspired by [this](https://advances.sciencemag.org/content/6/5/eaay4312) paper.

In [1]:
import pyiron

In [2]:
pr = pyiron.Project("MgH")

# Mg slab

In [3]:
ti = pr.create_ase_bulk("Mg", orthorhombic = True)
ti.plot3d()

NGLWidget()

Swap axes to match hydride slab.

In [4]:
ti.positions[:, (1, 2)] = ti.positions[:, (2, 1)]
ti.cell[1,1], ti.cell[2,2] = ti.cell[2,2], ti.cell[1,1]
ti.set_repeat([2,1,3])
ti.plot3d()

NGLWidget()

# MgH Slab

In [5]:
tih_proto = pr.create_ase_bulk("Al", cubic = True)
tih_proto[:] = "Mg"
tih_proto.plot3d()

NGLWidget()

In [6]:
import numpy as np
h_proto = tih_proto.copy()
h_proto[:] = "H"
h_proto.positions[:, :] += np.array((.25, .25, .25)) * tih_proto.cell[1,1]
wrong_I = h_proto.get_scaled_positions()[:, 2] > .5
h_proto.positions[wrong_I, 0] += .5 * tih_proto.cell[1,1]
h_proto.center_coordinates_in_unit_cell()
h_proto.plot3d()

NGLWidget()

In [7]:
tih = tih_proto + h_proto

In [8]:
pyiron.pyiron_to_ase(tih)

Atoms(symbols='Mg4H4', pbc=True, cell=[4.05, 4.05, 4.05])

In [9]:
import ase

In [10]:
ase.build.surface(pyiron.pyiron_to_ase(tih), (1,1,0), 4, periodic = True)

Atoms(symbols='Mg4H4Mg4H4Mg4H4Mg4H4', pbc=True, cell=[5.727564927611035, 4.05, 11.45512985522207])

In [11]:
hydride = pyiron.ase_to_pyiron(ase.build.surface(pyiron.pyiron_to_ase(tih), (1,1,0), 4, periodic = True))
hydride.center_coordinates_in_unit_cell()

Mg: [0. 0. 0.]
Mg: [4.2956737  2.025      1.43189123]
Mg: [1.43189123 2.025      1.43189123]
Mg: [2.86378246e+00 0.00000000e+00 2.67023049e-17]
H: [0.         3.0375     1.43189123]
H: [2.86378246 1.0125     1.43189123]
H: [0.         1.0125     1.43189123]
H: [2.86378246 3.0375     1.43189123]
Mg: [2.86378246 0.         2.86378246]
Mg: [1.43189123 2.025      4.2956737 ]
Mg: [4.2956737 2.025     4.2956737]
Mg: [-6.31074821e-17  0.00000000e+00  2.86378246e+00]
H: [2.86378246 3.0375     4.2956737 ]
H: [0.        1.0125    4.2956737]
H: [2.86378246 1.0125     4.2956737 ]
H: [0.        3.0375    4.2956737]
Mg: [0.         0.         5.72756493]
Mg: [4.2956737  2.025      7.15945616]
Mg: [1.43189123 2.025      7.15945616]
Mg: [2.86378246 0.         5.72756493]
H: [0.         3.0375     7.15945616]
H: [2.86378246 1.0125     7.15945616]
H: [0.         1.0125     7.15945616]
H: [2.86378246 3.0375     7.15945616]
Mg: [2.86378246 0.         8.59134739]
Mg: [ 1.43189123  2.025      10.02323862]
M

In [12]:
hydride.plot3d()

NGLWidget()

In [13]:
h_proto.positions

array([[1.0125, 1.0125, 1.0125],
       [3.0375, 3.0375, 3.0375],
       [1.0125, 1.0125, 3.0375],
       [3.0375, 3.0375, 1.0125]])

In [14]:
ti.cell, hydride.cell

(array([[ 6.42      ,  0.        ,  0.        ],
        [ 0.        ,  5.21304   ,  0.        ],
        [ 0.        ,  0.        , 16.67964928]]),
 array([[ 5.72756493,  0.        ,  0.        ],
        [ 0.        ,  4.05      ,  0.        ],
        [ 0.        ,  0.        , 11.45512986]]))

In [15]:
hydride.cell[2,2] += ti.cell[2,2]
hydride.positions[:, 2] += ti.cell[2,2]

In [16]:
slab = hydride + ti

Final Structure is model II form the paper.

In [17]:
slab.repeat([4,4,1]).plot3d()

NGLWidget()

In [18]:
pr.remove_jobs(recursive=True)

In [19]:
j = pr.create_job(pr.job_type.Lammps, "Mg_model2")
j.structure = slab
j.structure.pbc[2] = True

In [20]:
j.potential = j.list_potentials()[0]

In [21]:
j.calc_minimize(pressure = 0)

In [22]:
len(j.structure)

56

In [23]:
j.structure

Mg: [ 0.          0.         16.67964928]
Mg: [ 4.2956737   2.025      18.11154051]
Mg: [ 1.43189123  2.025      18.11154051]
Mg: [ 2.86378246  0.         16.67964928]
H: [ 0.          3.0375     18.11154051]
H: [ 2.86378246  1.0125     18.11154051]
H: [ 0.          1.0125     18.11154051]
H: [ 2.86378246  3.0375     18.11154051]
Mg: [ 2.86378246  0.         19.54343174]
Mg: [ 1.43189123  2.025      20.97532297]
Mg: [ 4.2956737   2.025      20.97532297]
Mg: [-6.31074821e-17  0.00000000e+00  1.95434317e+01]
H: [ 2.86378246  3.0375     20.97532297]
H: [ 0.          1.0125     20.97532297]
H: [ 2.86378246  1.0125     20.97532297]
H: [ 0.          3.0375     20.97532297]
Mg: [ 0.         0.        22.4072142]
Mg: [ 4.2956737   2.025      23.83910544]
Mg: [ 1.43189123  2.025      23.83910544]
Mg: [ 2.86378246  0.         22.4072142 ]
H: [ 0.          3.0375     23.83910544]
H: [ 2.86378246  1.0125     23.83910544]
H: [ 0.          1.0125     23.83910544]
H: [ 2.86378246  3.0375     23.83910

In [24]:
j.run()

The job Mg_model2 was saved and received the ID: 5920677


Periodic boundary conditions in $z$ force a stacking fault at the second interface and the hydrogen position does match any of the three models in the paper (it's missing one half plane to model II).

In [25]:
j.animate_structure()

NGLWidget(max_frame=109)

In [26]:
j.get_structure().repeat([1,1,2]).plot3d()

NGLWidget()

[Here](https://journals.aps.org/prb/pdf/10.1103/PhysRevB.76.064207) is a DFT paper that investigates the three models referred to in the original paper and studies their relative stability.